### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by jiangguiwen** [shaojianye/GD#2]
the link  of https://pan.baidu.com/s/1sl6lF9z is invalid，could send the valid link address？

**Comment by shaojianye** [comment]
很抱歉对您造成的不变，关于链接失效的问题，可在此博文中获得最新补链：https://www.jianshu.com/p/0039d1509593

**Comment by daxiong844** [comment]
项目下载下来了，我想直接在项目的基础上学习，但是修改了源码以后，运行的时候，还是显示原来的内容，即使我把app目录删除了，也可以运行。不知道是啥原因

**Comment by shaojianye** [comment]
我猜你是在安卓平台上进行的调试，在安卓端只要编译一次，就可以脱离npm服务，如果需要调试最新的代码效果，则需要调出调试菜单，选择reload选项即可。当然，正常情况下我们会开启热更新功能，当代码变化时，切换回模拟器后会自动进行相应的渲染。

**Comment by shaojianye** [comment]
已解决
